DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS COMMENTS;

CREATE TABLE AUTHORS
(
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
    FULL_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE GENRES
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE BOOKS
(
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE     VARCHAR(255) NOT NULL,
    AUTHOR_ID BIGINT       NOT NULL,
    GENRE_ID  BIGINT       NOT NULL
);

CREATE TABLE COMMENTS
(
    ID      BIGINT AUTO_INCREMENT PRIMARY KEY,
    BOOK_ID BIGINT       NOT NULL,
    TEXT    VARCHAR(255) NOT NULL
);

ALTER TABLE BOOKS
    ADD CONSTRAINT BOOK_AUTHOR_FK
        FOREIGN KEY (AUTHOR_ID)
            REFERENCES AUTHORS (ID) ON DELETE CASCADE;

ALTER TABLE BOOKS
    ADD CONSTRAINT BOOK_GENRE_FK
        FOREIGN KEY (GENRE_ID)
            REFERENCES GENRES (ID) ON DELETE CASCADE;

ALTER TABLE COMMENTS
    ADD CONSTRAINT COMMENT_BOOK_FK
        FOREIGN KEY (BOOK_ID)
            REFERENCES GENRES (ID) ON DELETE CASCADE;